AWSTemplateFormatVersion: '2010-09-09'
Description: AWS AppSync Private API with DynamoDB backend

Parameters:
  APIName:
    Type: String
    Default: MyPrivateAppSyncAPI
  TableName:
    Type: String
    Default: ItemsTable
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod

Resources:

  #-------------------------------------------------------
  # DynamoDB Table
  #-------------------------------------------------------
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${TableName}-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      Tags:
        - Key: Environment
          Value: !Ref Environment

  #-------------------------------------------------------
  # AppSync IAM Role (allows access to DynamoDB)
  #-------------------------------------------------------
  AppSyncDynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${APIName}-appsync-dynamodb-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AppSyncDynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:DeleteItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt DynamoDBTable.Arn
                  - !Sub '${DynamoDBTable.Arn}/index/*'

  #-------------------------------------------------------
  # AppSync GraphQL API (PRIVATE visibility)
  #-------------------------------------------------------
  AppSyncAPI:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Sub '${APIName}-${Environment}'
      AuthenticationType: API_KEY
      Visibility: PRIVATE
      LogConfig:
        CloudWatchLogsRoleArn: !GetAtt AppSyncLogsRole.Arn
        FieldLogLevel: ERROR
      Tags:
        - Key: Environment
          Value: !Ref Environment

  #-------------------------------------------------------
  # CloudWatch Logs Role for AppSync
  #-------------------------------------------------------
  AppSyncLogsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs

  #-------------------------------------------------------
  # API Key
  #-------------------------------------------------------
  AppSyncAPIKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      Description: API Key for Private AppSync API
      # You might need to update this
      Expires: 1787788800 # August 26, 2026

  #-------------------------------------------------------
  # GraphQL Schema
  #-------------------------------------------------------
  AppSyncSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      Definition: |
        type Item {
          id: ID!
          name: String!
          description: String
          createdAt: String
        }

        input CreateItemInput {
          id: ID!
          name: String!
          description: String
        }

        input UpdateItemInput {
          id: ID!
          name: String
          description: String
        }

        type Query {
          getItem(id: ID!): Item
          listItems: [Item]
        }

        type Mutation {
          createItem(input: CreateItemInput!): Item
          updateItem(input: UpdateItemInput!): Item
          deleteItem(id: ID!): Item
        }

        schema {
          query: Query
          mutation: Mutation
        }

  #-------------------------------------------------------
  # Data Source (DynamoDB)
  #-------------------------------------------------------
  AppSyncDynamoDBDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      Name: ItemsDynamoDBDataSource
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncDynamoDBRole.Arn
      DynamoDBConfig:
        AwsRegion: !Ref AWS::Region
        TableName: !Ref DynamoDBTable

  #-------------------------------------------------------
  # Resolvers
  #-------------------------------------------------------

  # --- GetItem Resolver ---
  GetItemResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      TypeName: Query
      FieldName: getItem
      DataSourceName: !GetAtt AppSyncDynamoDBDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: '1.0.0'
      Code: |
        import { util } from '@aws-appsync/utils';
        export function request(ctx) {
          return {
            operation: 'GetItem',
            key: util.dynamodb.toMapValues({ id: ctx.args.id }),
          };
        }
        export function response(ctx) {
          return ctx.result;
        }

  # --- ListItems Resolver ---
  ListItemsResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      TypeName: Query
      FieldName: listItems
      DataSourceName: !GetAtt AppSyncDynamoDBDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: '1.0.0'
      Code: |
        import { util } from '@aws-appsync/utils';
        export function request(ctx) {
          return { operation: 'Scan' };
        }
        export function response(ctx) {
          return ctx.result.items;
        }

  # --- CreateItem Resolver ---
  CreateItemResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      TypeName: Mutation
      FieldName: createItem
      DataSourceName: !GetAtt AppSyncDynamoDBDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: '1.0.0'
      Code: |
        import { util } from '@aws-appsync/utils';
        export function request(ctx) {
          const item = { ...ctx.args.input, createdAt: util.time.nowISO8601() };
          return {
            operation: 'PutItem',
            key: util.dynamodb.toMapValues({ id: ctx.args.input.id }),
            attributeValues: util.dynamodb.toMapValues(item),
          };
        }
        export function response(ctx) {
          return ctx.result;
        }

  # --- UpdateItem Resolver ---
  UpdateItemResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      TypeName: Mutation
      FieldName: updateItem
      DataSourceName: !GetAtt AppSyncDynamoDBDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: '1.0.0'
      Code: |
        import { util } from '@aws-appsync/utils';
        export function request(ctx) {
          const { id, ...values } = ctx.args.input;
          const expressionNames = {};
          const expressionValues = {};
          let updateExpression = 'SET';
          let first = true;
          for (const [key, value] of Object.entries(values)) {
            if (value !== null && value !== undefined) {
              const prefix = first ? ' ' : ', ';
              updateExpression += `${prefix}#${key} = :${key}`;
              expressionNames[`#${key}`] = key;
              expressionValues[`:${key}`] = util.dynamodb.toDynamoDB(value);
              first = false;
            }
          }
          return {
            operation: 'UpdateItem',
            key: util.dynamodb.toMapValues({ id }),
            update: { expression: updateExpression, expressionNames, expressionValues },
          };
        }
        export function response(ctx) {
          return ctx.result;
        }

  # --- DeleteItem Resolver ---
  DeleteItemResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncAPI.ApiId
      TypeName: Mutation
      FieldName: deleteItem
      DataSourceName: !GetAtt AppSyncDynamoDBDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: '1.0.0'
      Code: |
        import { util } from '@aws-appsync/utils';
        export function request(ctx) {
          return {
            operation: 'DeleteItem',
            key: util.dynamodb.toMapValues({ id: ctx.args.id }),
          };
        }
        export function response(ctx) {
          return ctx.result;
        }

Outputs:
  GraphQLApiId:
    Description: AppSync GraphQL API ID
    Value: !GetAtt AppSyncAPI.ApiId
  GraphQLApiArn:
    Description: AppSync GraphQL API ARN
    Value: !Ref AppSyncAPI
  GraphQLEndpoint:
    Description: AppSync GraphQL Endpoint URL
    Value: !GetAtt AppSyncAPI.GraphQLUrl
  DynamoDBTableName:
    Description: DynamoDB Table Name
    Value: !Ref DynamoDBTable
  APIKey:
    Description: AppSync API Key
    Value: !GetAtt AppSyncAPIKey.ApiKey
