
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}


server {
    listen 443 ssl;
    server_name appsync.dev.example.com;

    ssl_certificate     /etc/nginx/ssl/selfsigned.crt;
    ssl_certificate_key /etc/nginx/ssl/selfsigned.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;

    resolver 169.254.169.253 valid=30s ipv6=off;

    # ---------- ALB health check ----------
    location /health {
        access_log off;
        return 200 'healthy\n';
        add_header Content-Type text/plain;
    }

    # ---------- Proxy to AppSync Private API ----------
    location /graphql {

        set $appsync_endpoint "xxxxxxxxxxxx.appsync-realtime-api.us-east-1.amazonaws.com";

        set $upstream_url_log https://$appsync_endpoint$request_uri;

        proxy_pass https://$appsync_endpoint$request_uri;
        proxy_ssl_server_name on;

        # CRITICAL: route to the correct Private API
        proxy_set_header Host             $appsync_endpoint;
        proxy_set_header X-AppSync-Domain xxxxxxxxxxxx.appsync-api.us-east-1.amazonaws.com;

        # Pass through all client headers (x-api-key, Authorization, etc.)
        proxy_pass_request_headers on;
        proxy_ssl_session_reuse off;
        proxy_buffering off;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;


        # Standard forwarding headers
        proxy_set_header X-Real-IP        $remote_addr;
        proxy_set_header X-Forwarded-For  $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;

        # Timeouts
        proxy_connect_timeout  10s;
        proxy_read_timeout     30s;
        proxy_send_timeout     30s;
    }

}