user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log debug;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    underscores_in_headers on;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    'status=$status bytes=$body_bytes_sent '
                    'referer="$http_referer" ua="$http_user_agent" '
                    'request_uri="$request_uri" args="$args" '
                    'upstream_addr="$upstream_addr" upstream_status="$upstream_status" '
                    'upstream_response_time="$upstream_response_time" '
                    'upstream_connect_time="$upstream_connect_time" '
                    'upstream_url_log="$upstream_url_log" '
                    'ssl="$ssl_protocol/$ssl_cipher"';
    access_log  /var/log/nginx/access.log main;
    sendfile        on;
    tcp_nopush      on;
    keepalive_timeout  65;
    types_hash_max_size 4096;
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    include       /etc/nginx/conf.d/*.conf;
}